### ISSUE TITLE
1. Test Simstar Executable

### ISSUE THREAD

**Issue by afurkany** [BLG638-Project/final-project-2022#8]
Merhabalar,

Environment'ı exe ile kurdum ve açtığımda alttaki gibi bir görüntü ile uygulama başlıyor. Çevre içerisinde biraz tur attım ama herhangi bir araç göremedim. Araç oluşturmak için ek bir şey mi yapmamız gerekiyor yoksa kurulum sırasında herhangi bir hata almamış olsam da bu noktada mı bir sıkıntı olabilir? Açıklamalardaki gibi bir görüntü elde edemiyorum maalesef. Windows ortamında çalışıyorum.

![test1](https://user-images.githubusercontent.com/68605969/170829383-7d4eb811-9276-4ea3-a8a2-c40b919cbd87.png)

Şimdiden teşekkür ederim.

**Comment by resuldagdanov** [comment]
**Türkçe:**

Sayın @afurkany,

Eğitim için _**training_example/train.py**_ çalıştırıldığında bot arabaları piste yerleştirmektedir. Bu arabaların başlangıç yönelimlerini, konumlarını, başlangıç ve hedef hızlarını değiştirmek isterseniz _**training_example/train.py**_ satır 73-81 ve _**training_example/simstarEnv.py**_ satır 292-308 arasındaki değişkenleri değiştirebilirsiniz.

Ek olarak arabalar _**self.client.spawn_vehicle()**_ fonksiyonu ile konumlandırılmaktadır.

Rica ederiz.

-----------------------------------------------------------
**English:**

Dear @afurkany,

You can use  _**training_example/train.py**_ for training an example RL model; this script will automatically spawn rule-based bot vehicles on the track. In order to change the initial orientation, speed, position, and desired speed of these vehicles, _**training_example/train.py**_ script lines 73-81 and _**training_example/simstarEnv.py**_ script lines 292-308 could be modified.

In advance, all vehicles in the simulation are spawned with _**self.client.spawn_vehicle()**_ function.

Thanks.

-----------------------------------------------------------
_**training_example/train.py**_ line ~74:
>     opponent_positions = [
>         simstar.PoseData(1288.012085, -887.185735, yaw=-3.08)
>     ]

_**training_example/simstarEnv.py**_ line ~293:
>  new_agent = self.client.spawn_vehicle_to(
>                             vehicle_pose=self.opponent_poses[i],
>                             initial_speed=0,
>                             set_speed=self.agent_speeds[i],
>                             vehicle_type=simstar.EVehicleType.F1Racing,
>                         )

**Comment by afurkany** [comment]
Sayın @resuldagdanov 

Cevabınız ve verdiğiniz bilgiler için teşekkür ederim. Araçları eğitim esnasında gördüğümüz için bu durumda açılış ekranının ilk etapta bu şekilde olmasında sorun yok diyebiliriz. Eğitimi başlatabiliyor olmamız yeterli.

Tekrar teşekkürler.
