### ISSUE TITLE
Sensör testi ve manuel araç kullanma

### ISSUE THREAD

**Issue by afurkany** [BLG638-Project/final-project-2022#9]
Merhabalar,

Açıklamalar kısmında 2. Sensors başlığı altında sensör açıklamaları yapılmış.

train.py kodunu çalıştırarak sistemi başlatabildim. Sensörleri test edebilmemiz için ek bir şey yapmamız gerekiyor mu, yoksa train.py kodunun sorunsuz bir şekilde çalışıyor olması yeterli mi?

Ayrıca environment'ı exe ile başlatmamızın ardından aracı arayüz üzerinden çağırıp kendimiz klavye tuşları ile kullanabiliyor muyuz?

Teşekkür ederim.

**Comment by resuldagdanov** [comment]
**Türkçe:**

Sayın @afurkany,

_**training_example/train.py**_ kodunu çalıştırdığınızda verilen sensörlerin hepsi istenilen formatta ve frekansta çalışmaktadır. Sorunsuz çalıştığınından emin olmak isterseniz **_training_example/simstarEnv.py_** kodundaki _**get_simstar_obs()**_ fonksiyonuna göz atabilirsiniz.

Rica ederiz.

--------------------------------------------------------
**English:**

Dear @afurkany,

By running _**training_example/train.py**_ all given sensors will be working in a required format and frequency. In order to make sure that all sensors are working properly, you can take a look at **_training_example/simstarEnv.py_** script _**get_simstar_obs()**_ function.

Thanks.

**Comment by afurkany** [comment]
Sayın **@resuldagdanov** 

Training'i çalıştırırken sensörler ile ilgili herhangi bir hata almıyorum yine de belirttiğiniz kısımlara da ayrıca göz atacağım.

Ek bilgi olarak şunu da belirtebilirim. Simulatör'ü açtığımızda 1-6 tuşlarına bastığımızda bazı arayüzler açılıyor. Oradan simulatöre araç ekleyip klavye tuşları ile de aracı sürebiliyoruz.

Cevabınız için teşekkür ederim.

**Comment by resuldagdanov** [comment]
Added a comment line as https://github.com/BLG638-Project/final-project-2022/commit/c2de0417b6539983c4c79a7e89920bf92a4fc482 . Try it and have fun :)
